### ISSUE TITLE
Błąd z licencją

### ISSUE THREAD

**Issue by Weberowsky** [Titon191/infinity.db#1]
a przez przypadek cos chyba napisalem cofam to

**Comment by Titon191** [comment]
Jakie quick.db? ja tam nic nie wiem 😏
_Spójrz jeszcze raz w kod_

**Comment by Weberowsky** [comment]
> Jakie quick.db? ja tam nic nie wiem 😏
> _Spójrz jeszcze raz w kod_

Tja

**Comment by Titon191** [comment]
i chodz na dc
